# Generated by Django 6.0.3 on 2026-03-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color_marcador', models.CharField(default='#4d4383', max_length=20)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='mapas.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=17, max_digits=21)),
                ('longitud', models.DecimalField(decimal_places=17, max_digits=22)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='mapas.subcategoria')),
            ],
        ),
    ]
